import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getInstallationOctokit } from "@/lib/github-app";
import { isAllowedDbtPath, normalizeRepoPath } from "@/lib/dbt-paths";
import { requireSession } from "@/lib/session";

type ProposedChange = {
  path: string;
  content: string;
};

type CreatePrPayload = {
  connectionId: string;
  title: string;
  body?: string;
  changes: ProposedChange[];
};

function parseOwnerAndRepo(fullName: string) {
  const [owner, repo] = fullName.split("/");
  if (!owner || !repo) {
    throw new Error("Invalid repository full name");
  }
  return { owner, repo };
}

function createBranchName(title: string) {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
  const timestamp = Date.now();
  return `dbt-generator/${slug || "generated"}-${timestamp}`;
}

async function getContentSha(params: {
  octokit: ReturnType<typeof getInstallationOctokit>;
  owner: string;
  repo: string;
  path: string;
  ref: string;
}) {
  try {
    const result = await params.octokit.request("GET /repos/{owner}/{repo}/contents/{path}", {
      owner: params.owner,
      repo: params.repo,
      path: params.path,
      ref: params.ref,
    });

    if (!Array.isArray(result.data) && "sha" in result.data) {
      return result.data.sha;
    }
    return undefined;
  } catch (error) {
    const maybeError = error as { status?: number };
    if (maybeError.status === 404) {
      return undefined;
    }
    throw error;
  }
}

export async function POST(request: Request) {
  const session = await requireSession(request);
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let payload: CreatePrPayload;
  try {
    payload = (await request.json()) as CreatePrPayload;
  } catch {
    return NextResponse.json({ error: "Invalid payload" }, { status: 400 });
  }

  if (!payload.connectionId || !payload.title?.trim() || !payload.changes?.length) {
    return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
  }

  const normalizedChanges = payload.changes.map((change) => ({
    path: normalizeRepoPath(change.path),
    content: change.content,
  }));

  if (
    normalizedChanges.some(
      (change) => !change.path || !isAllowedDbtPath(change.path) || typeof change.content !== "string",
    )
  ) {
    return NextResponse.json(
      { error: "One or more paths are outside the dbt allowlist" },
      { status: 400 },
    );
  }

  const connection = await prisma.repoConnection.findFirst({
    where: {
      id: payload.connectionId,
      userId: session.user.id,
    },
  });
  if (!connection) {
    return NextResponse.json({ error: "Connection not found" }, { status: 404 });
  }

  const { owner, repo } = parseOwnerAndRepo(connection.repositoryFullName);
  const octokit = getInstallationOctokit(Number(connection.installationId));
  const baseBranch = connection.defaultBranch;
  const branchName = createBranchName(payload.title);

  try {
    const baseRef = await octokit.request("GET /repos/{owner}/{repo}/git/ref/{ref}", {
      owner,
      repo,
      ref: `heads/${baseBranch}`,
    });

    await octokit.request("POST /repos/{owner}/{repo}/git/refs", {
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseRef.data.object.sha,
    });

    for (const change of normalizedChanges) {
      const existingSha = await getContentSha({
        octokit,
        owner,
        repo,
        path: change.path,
        ref: branchName,
      });

      await octokit.request("PUT /repos/{owner}/{repo}/contents/{path}", {
        owner,
        repo,
        path: change.path,
        branch: branchName,
        message: `chore(dbt): update ${change.path}`,
        content: Buffer.from(change.content, "utf8").toString("base64"),
        sha: existingSha,
      });
    }

    const pr = await octokit.request("POST /repos/{owner}/{repo}/pulls", {
      owner,
      repo,
      title: payload.title.trim(),
      body: payload.body?.trim() || "Generated by dbt-generator.",
      base: baseBranch,
      head: branchName,
      draft: true,
    });

    return NextResponse.json({
      pullRequest: {
        url: pr.data.html_url,
        number: pr.data.number,
      },
    });
  } catch {
    return NextResponse.json(
      {
        error:
          "Failed to create draft PR. Verify installation access, branch protection rules, and file paths.",
      },
      { status: 500 },
    );
  }
}
